language: elixir
elixir:
    - 1.2.0
otp_release:
  - 18.0

before_script:
  - mix local.hex --force
  - mix deps.get

script: mix test

after_script:
    - MIX_ENV=docs mix deps.get
    - MIX_ENV=docs mix inch.report
